[package]
name = "svmm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
polyline = "0.11.0"
reqwest = { version = "0.13.4", features = ["json", "query"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "time", "sync", "fs"] }
usage = { package = "usage-rs", version = "6.0.0", features = ["completions"] }

[dev-dependencies]
usage = { package = "usage-rs", version = "6.0.0", features = ["test"] }
